services:
  db_serv:
    image: postgres    
    container_name: local_postgre
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2015
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  # pgadmin_serv:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin4_app
  #   restart: always
  #   ports:
  #     - "8888:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: postgres
  #     PGADMIN_DEFAULT_PASSWORD: 2015
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  # pgadmin-data: