services:
  db_serv:
    image: postgres    
    container_name: local_postgre
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2015
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    networks:
      - kezekshi_net

networks:
  kezekshi_net:
    # Объявляем, что эта сеть может использоваться другими
    name: kezekshi_net_global 
    driver: bridge

volumes:
  local_pgdata: