# networks:
#   pgre-db-network:
#     driver: bridge

services:
  db_serv:
    image: postgres
    # networks:
    #   - pgre-db-network
    container_name: local_postgre
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2015
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin_serv:
    image: dpage/pgadmin4
    # networks:
    #   - pgre-db-network
    container_name: pgadmin4_app
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: bag.dat@live.ru
      PGADMIN_DEFAULT_PASSWORD: Qwerty1+
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data: